---
name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  pytest:
    uses: colcon/ci/.github/workflows/pytest.yaml@cottsay/null-secret
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
